[package]
name = "fshell-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "External process fallback and glob for fshell"
repository.workspace = true

[dependencies]
fshell-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fshell-engine = { workspace = true }
fshell-sandbox = { workspace = true }
indexmap = { workspace = true }
fshell-hash = { workspace = true, features = ["std"] }
ustr = { workspace = true }
libc = { workspace = true }
fshell-tty = { workspace = true }
miette = { workspace = true }
bytes = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
criterion = { workspace = true }
fshell-builtins = { path = "../fshell-builtins" }

[[bench]]
name = "bridge"
harness = false
