[package]
name = "fshell-ls"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Git-aware ls library for fshell"
repository.workspace = true

[dependencies]
terminal_size = { workspace = true }
libc = { workspace = true }
unicode-width = { workspace = true }
fshell-git = { path = "../fshell-git" }
rayon = { workspace = true }

[lints]
workspace = true
